apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  type: LoadBalancer  # Cambiar a LoadBalancer si usas un proveedor de nube
  ports:
    - name: load-balancer  # Nombre único para este puerto
      port: 80          # Puerto expuesto por el servicio
      nodePort: 30080   # Puerto del nodo (opcional, Kubernetes asignará uno si no lo defines)